### ISSUE TITLE
unable to build

### ISSUE THREAD

**Issue by phicore** [zenith391/zgt#1]
Sorry i'm quite new to zig but i'm unable to build zgt on windows.

![image](https://user-images.githubusercontent.com/6534441/114606854-1bca3500-9c9c-11eb-8078-d9d1d35a7764.png)

I also tried with the syntax I found on zig documentation

```
usingnamespace @import("std.os.windows.user32");
usingnamespace @import("std.os.windows.kernel32");
```

same result

I was able to build other simple projects like the pacman.zig that use sokol libraries

I tried with zig 0.7.1 and 0.8.0-current, same results.

**Comment by zenith391** [comment]
Fixed it. However currently the `win32` backend is still experimental and will be rewritten soon.

**Comment by phicore** [comment]
much better

The calculator shows up, buttons are clickable but no computation is displayed

**Comment by zenith391** [comment]
By the way, the `win32` backend now allows buttons to be clicked.
