### ISSUE TITLE
Fail to build executable with `zigmod` and the latest `zig`

### ISSUE THREAD

**Issue by v1nh1shungry** [zenith391/zgt#10]
I followed https://github.com/zenith391/zgt/wiki/Installation to set up `zgt`. And when I tried building the first application I got the following error:

```bash
$ zig build run
./deps.zig:69:36: error: no member named 'path' in struct 'std.build.Pkg'
        .pkg = Pkg{ .name = "zgt", .path = .{ .path = dirs._deeztnhr07fk ++ "/src/main.zig" }, .dependencies = null },
```

I use the current latest `zig`, 

```bash
$ zig version
0.10.0-dev.2751+08459ff1c
```
And in the latest version, there is no longer `path` in the `std.build.Pkg`:
https://github.com/ziglang/zig/blob/08459ff1c21d546c55e2ae954126e121ee88972e/lib/std/build.zig#L1355-L1359

After I replaced `path` with `source`, everything is okay.

I don't know which version of `zig` you're using, and I can't find anything about this in the documentation. Maybe I missed. If not, please consider specify the `zig` version in the document. Or migrate to the latest `zig` and fix the `deps.zig`.

**Comment by zenith391** [comment]
Yea, it's due to a breaking change in Zig master (`path` got renamed to `source` for clarity)
Fixed in 1630366
