### ISSUE TITLE
zgt works great on PinePhone

### ISSUE THREAD

**Issue by lupyuen** [zenith391/zgt#8]
Hi: Thanks for the great work on zgt! Running it on PinePhone was incredibly easy, only took me a few hours to do this...

https://github.com/lupyuen/zig-pinephone-gui

I hope this will inspire PinePhone devs to create mobile apps with Zig and zgt. Thanks again :-)

**Comment by zenith391** [comment]
That's awesome! As I don't have a PinePhone, I didn't knew if it could work on it but looks like it runs the GTK backend just fine. So now zgt runs on 4 platforms: Windows, Linux, PinePhone and WebAssembly :smile:

**Comment by lupyuen** [comment]
FYI I have written an article to help PinePhone Devs get started quickly on zgt:

["Build a PinePhone App with Zig and zgt"](https://lupyuen.github.io/articles/pinephone)

Thanks again :-)

**Comment by lupyuen** [comment]
Some interesting comments on Hacker News...

https://news.ycombinator.com/item?id=31863269
